#!/bin/bash
vcs +v2k -debug_all -sverilog -full64 \
-P $NOVAS_HOME/share/PLI/VCS/LINUX64/verdi.tab \
   $NOVAS_HOME/share/PLI/VCS/LINUX64/pli.a \
+incdir+../tb \
-f ../flist/flist \
+notimingcheck \
+nospecify \
-l sim.log \
-top tb_top \
-R \
